name: spin CI

on: workflow_dispatch

jobs:
  take-screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.4
      - run: sudo apt-get install graphicsmagick
      - run: |
          git config --global user.email "4769034+nianjie@users.noreply.github.com"
          git config --global user.name "nj"
      - run: npm ci
      - run: npm run
        env:
          GITHUB_API_TOKEN: ${{ secrets.GIST_GITHUB_API_TOKEN }}
      - name: Upload main.gif
        uses: actions/upload-artifact@v2.2.1
        with:
          name: main.gif
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ github.workspace }}/${{ env.gisttoken }}/main.gif
          retention-days: 1
        env:
          gisttoken: 032161472173202c27337763fe1d9d56
      - run: |
          ls -alrtF ${{ github.workspace }}
          ls -alrtF ${{ github.workspace }}/${{ env.gisttoken }}