name: spin CI

on: workflow_dispatch

env:
  gist: 032161472173202c27337763fe1d9d56
  gist_file_name: main.gif

jobs:
  take-screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.4
      - run: sudo apt-get install graphicsmagick
      - run: |
          git config --global user.email "4769034+nianjie@users.noreply.github.com"
          git config --global user.name "nj"
      - run: npm ci
      - run: npm run run
        env:
          GITHUB_API_TOKEN: ${{ secrets.GIST_GITHUB_API_TOKEN }}
      - run: |
          ls -alrtF ${{ github.workspace }}
          ls -alrtF ${{ github.workspace }}/${{ env.gist }}