name: update WOTD

on: workflow_dispatch

env:
  api_address: 'https://oxfordwotd.herokuapp.com/wotd/'

jobs:
  take-screenshot:
    runs-on: ubuntu-latest
    steps:
      - run: curl "${{ env.api_address }}"
