name: 'execute WOTD-update process.'

on:
  schedule:
    - cron:  '8 1 * * *'

env:
  api_address: ${{ secrets.WOTD_API_URL }}

jobs:
  take-screenshot:
    runs-on: ubuntu-latest
    steps:
      - run: curl "${{ env.api_address }}"
